"""empty message

Revision ID: 09f6fc0513ea
Revises: f95fd9067766
Create Date: 2024-04-14 09:35:19.974689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f6fc0513ea'
down_revision = 'f95fd9067766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plumbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plumbers', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
