"""Initial migration

Revision ID: 197945ce002a
Revises: 47f2dd637807
Create Date: 2024-04-07 04:25:45.942574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197945ce002a'
down_revision = '47f2dd637807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=14),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
