"""initial migration

Revision ID: 8bf0d91225e6
Revises: 
Create Date: 2024-03-29 13:42:03.969695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf0d91225e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plumber')
    op.drop_table('message')
    op.drop_table('job_offer')
    op.drop_table('base_user')
    op.drop_table('client')
    op.drop_table('ranking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.FLOAT(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('plumber_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['plumber_id'], ['plumber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['base_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=60), nullable=False),
    sa.Column('date_joined', sa.DATETIME(), nullable=False),
    sa.Column('phone_no', sa.INTEGER(), nullable=False),
    sa.Column('state', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_no'),
    sa.UniqueConstraint('username')
    )
    op.create_table('job_offer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('content', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('plumber_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['plumber_id'], ['plumber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('date_sent', sa.DATETIME(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('plumber_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['plumber_id'], ['plumber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plumber',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['base_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
