"""your_migration_message

Revision ID: 985cb2e6c777
Revises: a3f0d6044c50
Create Date: 2024-04-09 22:38:11.301756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985cb2e6c777'
down_revision = 'a3f0d6044c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_plumbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('plumber_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['plumber_id'], ['plumbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('message')
    op.drop_table('ranking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.FLOAT(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('plumber_id', sa.INTEGER(), nullable=True),
    sa.Column('job_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['plumber_id'], ['plumbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('date_sent', sa.DATETIME(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('plumber_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['plumber_id'], ['plumbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('job_plumbers')
    # ### end Alembic commands ###
