"""your_migration_message

Revision ID: b38a4066c436
Revises: 197945ce002a
Create Date: 2024-04-07 22:17:55.917175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38a4066c436'
down_revision = '197945ce002a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plumbers', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('service_areas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plumbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_areas', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('bio', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
