"""empty message

Revision ID: f95fd9067766
Revises: 985cb2e6c777
Create Date: 2024-04-11 15:07:08.216931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95fd9067766'
down_revision = '985cb2e6c777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_plumbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_assigned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_plumbers', schema=None) as batch_op:
        batch_op.drop_column('is_assigned')

    # ### end Alembic commands ###
